### ISSUE TITLE
tanh is not applied when im_size < 1024

### ISSUE THREAD

**Issue by AtsushiHashimoto** [odegeasslbc/FastGAN-pytorch#11]
Hi! Thank you for sharing the code of your great work!
Our team is enjoying the performance. 

By the way, I wonder about the `tanh` functions applied only with the netG output of `im_size==1024` (but not when `im_size==256` or `im_size==512`.

https://github.com/odegeasslbc/FastGAN-pytorch/blob/0e6ea568bc2f39a4e9c599ad9f9fd8f015c341b5/models.py#L177

https://github.com/odegeasslbc/FastGAN-pytorch/blob/0e6ea568bc2f39a4e9c599ad9f9fd8f015c341b5/models.py#L169

I guess that this is not a critical issue but just wanted to let you know.

**Comment by odegeasslbc** [comment]
Yes, thanks for pointing it out. I was experimenting about the usefulness of tanh and forget to add it back.

**Comment by AtsushiHashimoto** [comment]
Thanks!
