### ISSUE TITLE
LPIPS

### ISSUE THREAD

**Issue by kobeshegu** [odegeasslbc/FastGAN-pytorch#15]
How can I compute the Lpips with the code in LPIPS folder？THX.

**Comment by odegeasslbc** [comment]
Hi

Please refer to the code under the scripts folder here:
https://github.com/odegeasslbc/FastGAN-pytorch/blob/902a47397ae6a1dc23142aeda62ebaa00d5e87d2/scripts/find_nearest_neighbor.py#L48

It is how you can import from lpips. And once you initialize the module, you can calculate the score simply by:
import lpips
percept = lpips.PerceptualLoss(model='net-lin', net='vgg', use_gpu=True)
score = percept(gen_iamge, real_image).sum()
