### ISSUE TITLE
Nature Photograph Dataset

### ISSUE THREAD

**Issue by xl-sr** [odegeasslbc/FastGAN-pytorch#16]
Thank you for sharing your code; I really appreciate the clarity and simplicity in your implementation.

The "Nature Photograph" dataset which you use in the paper is not in provided few-shot-dataset.zip. Are there any copyright issues with the data, or could you also share it? If not, could you provide instructions on how to get the data? This would be great for reproducibility/comparison.

Thanks!

**Comment by odegeasslbc** [comment]
Hi

Thanks, the landscape images are from https://unsplash.com/ (high-quality wallpaper-like images), we acquired these images on our own and were worried about copyright issues, so I decided not to publish them. But I guess one can easily have a web crawler to download images from their website, as long as they make these images publicly available.

**Comment by xl-sr** [comment]
Did you simply download all images from the nature category? And which subset did you use for the few-shot experiments?

Maybe it would be possible that you don't share it publicly, but privately on demand? Would be great. Otherwise, a web crawler it is...

**Comment by odegeasslbc** [comment]
Sorry, I'm restricted by company rules to share this data set (as we are using this dataset to train several commerce models) (also I was not involved in the data collection work for this particular landscape image set).
