### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'Generator' object has no attribute 'se_512'

### ISSUE THREAD

**Issue by DerpyMan101** [odegeasslbc/FastGAN-pytorch#18]
When running this command `python train.py --path=C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\custom-images --im_size=128 --name=voice`

This is the output:

`Setting up Perceptual loss...
Loading model from: C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
Namespace(batch_size=8, ckpt='None', cuda=0, im_size=128, iter=50000, name='voice', path='C:\\Users\\Graham\\Desktop\\ICSCapstone\\FastGAN-pytorch-main\\custom-images', start_iter=0)
Setting up Perceptual loss...
Loading model from: C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
Setting up Perceptual loss...
Loading model from: C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
Setting up Perceptual loss...
Loading model from: C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
Setting up Perceptual loss...
Loading model from: C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
Setting up Perceptual loss...
Loading model from: C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
Setting up Perceptual loss...
Loading model from: C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
Setting up Perceptual loss...
Loading model from: C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
Setting up Perceptual loss...
Loading model from: C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\lpips\weights\v0.1\vgg.pth
...[net-lin [vgg]] initialized
...Done
  0%|                                                                                        | 0/50001 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 200, in <module>
    train(args)
  File "train.py", line 136, in train
    fake_images = netG(noise)
  File "C:\Users\Graham\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Graham\Desktop\ICSCapstone\FastGAN-pytorch-main\models.py", line 171, in forward
    feat_512 = self.se_512( feat_32, self.feat_512(feat_256) )
  File "C:\Users\Graham\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Generator' object has no attribute 'se_512'`

**Comment by odegeasslbc** [comment]
Sorry, the code is not well supported with the image size to be 128. You can set the size to be 256, the code will upscale all your training images by itself.
