### ISSUE TITLE
not support compare_ssim in skimage 0.18.2

### ISSUE THREAD

**Issue by torumitsutake** [odegeasslbc/FastGAN-pytorch#22]
Newer versions of skiimage cannot be run because the functions for calculating ssim have been changed.

```
ImportError: cannot import name 'compare_ssim' from 'skimage.measure' (/usr/local/var/pyenv/versions/image_generator/lib/python3.8/site-packages/skimage/measure/__init__.py)
```

**Comment by odegeasslbc** [comment]
Hi, please use another version of skimage. For example, I use:
pip install scikit-image==0.14.3

**Comment by ammar-deep** [comment]
A quick solution to the version problem can be changing the file lpips/__init__.py as follows

change default to: from skimage import measure (line 7)
change default to:  return (1 - measure.compare_ssim(p0, p1, data_range=range, multichannel=True)) / 2. (line 53)
