### ISSUE TITLE
Image distortion problem；

### ISSUE THREAD

**Issue by hahahaha-hash** [odegeasslbc/FastGAN-pytorch#23]
There are about 20 images in the training set, and the number of iterations is set to 50000. Most of the output result images are distorted. If I want to improve the quality of the images in the results, may I ask from what aspects can I consider this problem?

**Comment by odegeasslbc** [comment]
Sorry, I think in current stage, it is simply because the model is not good enough to get good image quality with your dataset. Maybe let's follow the academic literature and see if new methods will be proposed to improve it。
