### ISSUE TITLE
Failed to decompress dataset after downloading

### ISSUE THREAD

**Issue by yangyu615** [odegeasslbc/FastGAN-pytorch#29]
![image](https://user-images.githubusercontent.com/58797984/133266475-d760af11-79db-4443-9bfb-6224ea77891e.png)
According to the download address of the datasets you provided, there was an error when decompressing the dataset after downloading it. Is there any other way to share the dataset? Thank you very much!

**Comment by odegeasslbc** [comment]
could you make sure you uncompressed with the correct format, should be .zip, not .rar?

**Comment by yangyu615** [comment]
Thank you very much for your answer，I tried to download it again and  uncompressed it successfully. Maybe there was something wrong with the dataset when I first downloaded it.
                                                                                               yours sincerely,
                                                                                               Yu Yang
                                                                  
| |
杨杨杨
|
|
***@***.***
|
签名由网易邮箱大师定制
On 9/19/2021 03:47，Bingchen ***@***.***> wrote：

could you make sure you uncompressed with the correct format, should be .zip, not .rar?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
