### ISSUE TITLE
How to continue the training?

### ISSUE THREAD

**Issue by ruanjiyang** [odegeasslbc/FastGAN-pytorch#3]
Dear odegeasslbc,  how to continue the training?
For example, yesterday I had stopped the training at iter 25000. 
And today I wan to continue the training by following commands:
python train.py --name myImages --path "/myImages"  --batch_size 16  --start_iter 25001
and it looks that "--start_iter 25001“ doesn't work.   it still start the training from iter 0.

thanks.

**Comment by sainatarajan** [comment]
I think the loop runs only for the difference b/w the end_iter and start_iter. Before the loop starts executing, the weights are loaded. So this shouldn't be a problem.

**Comment by odegeasslbc** [comment]
Hi, have you make sure to also pass the "--ckpt /path/to/the/saved/checkpoint" config to the command? When you pass this pass, the code will try to load the pre-trained weights, you can check the code in line 120 at train.py: https://github.com/odegeasslbc/FastGAN-pytorch/blob/2a2e8d9d13ac01111645502cc903b7bff0031dc4/train.py#L120-L128 .

**Comment by ruanjiyang** [comment]
> Hi, have you make sure to also pass the "--ckpt /path/to/the/saved/checkpoint" config to the command? When you include this, the code will try to load the pre-trained weights, you can check the code in line 120 at train.py:
> 
> https://github.com/odegeasslbc/FastGAN-pytorch/blob/2a2e8d9d13ac01111645502cc903b7bff0031dc4/train.py#L120-L128
> 
> .

Dear odegeasslbc

Got your point. and it works well . :)

thanks so much.
