### ISSUE TITLE
Why the code use skip-layer channel-wise excitation to extracts feat_64, but the paper does not?

### ISSUE THREAD

**Issue by xuewengeophysics** [odegeasslbc/FastGAN-pytorch#30]
Hi. Thanks for your excellent research work.
I have a question why the code use skip-layer channel-wise excitation to extracts feat_64, but the paper does not?

feat_64  = self.se_64( feat_4, self.feat_64(feat_32) )

![image](https://user-images.githubusercontent.com/8676098/133745206-ba745a9a-43a2-453a-a1b9-9a833893323d.png)

**Comment by odegeasslbc** [comment]
It depends on how large your model is, in the paper the figure shows a model outputs at 256x256 resolution, but in the code its for 512 or 1024 resolution.

**Comment by xuewengeophysics** [comment]
> It depends on how large your model is, in the paper the figure shows a model outputs at 256x256 resolution, but in the code its for 512 or 1024 resolution.

Thanks very much.
