### ISSUE TITLE
Why the discriminator uses skip-layer channel-wise excitation in the code, but not in the paper?

### ISSUE THREAD

**Issue by xuewengeophysics** [odegeasslbc/FastGAN-pytorch#31]
Hi. Thanks for your excellent research work.
I have a question why the discriminator in the code uses skip-layer channel-wise excitation, but not in the paper?

feat_16 = self.se_2_16(feat_2, feat_16)
feat_32 = self.se_4_32(feat_4, feat_32)
feat_last = self.se_8_64(feat_8, feat_last)

![image](https://user-images.githubusercontent.com/8676098/133767969-5e5df840-4e47-4b0e-bf26-74301701fbae.png)

**Comment by odegeasslbc** [comment]
Just wanted to experiment its effect on D, which I found makes minor differences on many datasets.
