### ISSUE TITLE
Why training discriminator uses rec_img_small, in addition to decoder_big and decoder_part?

### ISSUE THREAD

**Issue by xuewengeophysics** [odegeasslbc/FastGAN-pytorch#32]
Hi. Thanks for your excellent research work.
I have a question why training discriminator uses decoder_small, in addition to decoder_big and decoder_part?
In my opinion, reconstruction loss does not use rec_img_small accroding to paper. Maybe I missed important information.

rec_img_big = self.decoder_big(feat_last)
rec_img_small = self.decoder_small(feat_small)
rec_img_part = self.decoder_part(feat_32[:,:,:8,:8])

![image](https://user-images.githubusercontent.com/8676098/133792828-3afd20d8-1b91-4c1e-839f-25c3442e19be.png)

**Comment by odegeasslbc** [comment]
Yeah, this "decoder_small" is an optional part, I just wanted to experiment on different structure configurations.
