### ISSUE TITLE
DiffAug color + LPIPS wrong range

### ISSUE THREAD

**Issue by lars76** [odegeasslbc/FastGAN-pytorch#33]
I found a slight problem with DiffAug and LPIPS.

PerceptualLoss expects images between [-1, +1] but by using DiffAug with the default color policy we get values below -1 and /or above +1.  This affects only the second argument of `percept(x, y)` because the first argument comes from the neural network with tanh.

This can be verified by inserting after line 40 in [train.py](https://github.com/odegeasslbc/FastGAN-pytorch/blob/main/train.py#L40) some print statements:

```
print("rec_all", rec_all.min(), rec_all.max()) # -0.9973, 0.9963
print("rec_small", rec_small.min(), rec_small.max()) # -0.9997, 0.9999
print("rec_part", rec_part.min(), rec_part.max()) # -1.0000, 0.9998
print("data", data.min(), data.max()) # -1.3135, 0.6860 -----> WRONG
```

**Comment by odegeasslbc** [comment]
I am not sure if clip the values into [-1, 1] will help improving the performance, it's worth trying out.
