### ISSUE TITLE
What's the difference of optimizerG.state_dict() and netG.state_dict(), thank you！

### ISSUE THREAD

**Issue by yangyu615** [odegeasslbc/FastGAN-pytorch#38]
What's the difference of optimizerG.state_dict() and netG.state_dict(), thank you！

**Comment by odegeasslbc** [comment]
optimizerG.state_dict() is for parameters of the optimizer, such as the momentums used by Adam optimizer,
netG.state_dict() is for the actual model's weights

**Comment by yangyu615** [comment]
Thank you very much for your reply.


| |
杨杨杨
|
|
***@***.***
|
签名由网易邮箱大师定制
On 12/27/2021 14:45，Bingchen ***@***.***> wrote：

optimizerG.state_dict() is for parameters of the optimizer, such as the momentums used by Adam optimizer,
netG.state_dict() is for the actual model's weights

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
