### ISSUE TITLE
Saved Models.

### ISSUE THREAD

**Issue by vsantjr** [odegeasslbc/FastGAN-pytorch#41]
Hello,
First of all, congrats for your nice work. 
Just to know what is the meaning of the saved models. I have trained with 50000 iterations and for each 10000 iterations a model is saved. Hence, we have `50000.pth` and `all_50000.pth`. Whats is the difference between them when generating new fake samples?
Best Regards.

**Comment by odegeasslbc** [comment]
Hi

'50000.pth' only has the generator and discriminator, 'all_50000.pth' contains optimizers which you can use later to resume the trainings.  There is no difference between the saved generator and discriminator

**Comment by vsantjr** [comment]
Hello,
Thank you for your response.
Regards.
