### ISSUE TITLE
.pkl instead of .pth

### ISSUE THREAD

**Issue by corlangerak** [odegeasslbc/FastGAN-pytorch#6]
How could FastGAN generate pickle .pkl files instead of .pth files.
Wouldn't there be more compatibility with stylegan2-ada? Or am I missing something? Could you convert this. or change in manually in the code?

**Comment by odegeasslbc** [comment]
Hi

You can use "torch.load()" to load the saved .pth file, which does not have any compatibility issue within the PyTorch environment. Actually '.pth' is not a file format, I just use it to represent files that are saved model weights.

I believe the "stylegan2-ada" you refer to is the official implementation, which uses TensorFlow, a different framework than PyTorch.
